server:
  port: 7070
spring:
  application:
    name: gccc-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/cher-yami/neo.git

          searchPaths: config-data
          default-label: main

  security:
    user:
      name: Cherman
      password: 202211951
